plugins {
    id 'java'
    id 'io.freefair.lombok' version '8.0.1' // Подключение плагина Lombok
}

group = 'com.skillbox'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.16.1'

}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
